name: Android Fastlane With Firebase App Distribution # Optional: Workflow Name 


on: 
  push: 
    branches:
      - main 
jobs:   # Groups together all the jobs that run in this workflow.
  distribute_to_firebase:  # Job Name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
 
      - name: Print JAVA_HOME
        run: |
          echo "JAVA_HOME is set to $JAVA_HOME"
          ls -l $JAVA_HOME 
          $JAVA_HOME/bin/java -version

      - name: Install Flutter 
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4 
          bundler-cache: true   
          working-directory: android
          
      - name: Compare Tokens
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          PERSONAL_TOKEN: "1//03g5YQDVlYFbhCgYIARAAGAMSNwF-L9IrX20DLbvpBTWBSFD2RBsILJ5Kk4Kcdb-sgIZ5UDV5_gB2mLqwnMaKvr58k_n9I83h0k8"  # Replace with your actual token for testing
        run: |
          if [ "$FIREBASE_CLI_TOKEN" == "$PERSONAL_TOKEN" ]; then
            echo "Tokens match!"
          else
            echo "Tokens do not match!"
          fi

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: "1//03g5YQDVlYFbhCgYIARAAGAMSNwF-L9IrX20DLbvpBTWBSFD2RBsILJ5Kk4Kcdb-sgIZ5UDV5_gB2mLqwnMaKvr58k_n9I83h0k8"
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/22.0.2-9/x64

         
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android 
       